WARNING 2020-07-28 09:33:41,022 log 13892 3796 Not Found: /
WARNING 2020-07-28 09:33:41,022 basehttp 13892 3796 "GET / HTTP/1.1" 404 2026
ERROR 2020-07-28 09:33:47,542 log 13892 3796 Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2020-07-28 09:33:47,544 basehttp 13892 3796 "GET /f/l/ HTTP/1.1" 500 118812
WARNING 2020-07-28 09:37:08,387 log 9236 12112 Not Found: /
WARNING 2020-07-28 09:37:08,387 basehttp 9236 12112 "GET / HTTP/1.1" 404 2026
ERROR 2020-07-28 09:37:20,324 log 9236 12112 Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2020-07-28 09:37:20,326 basehttp 9236 12112 "GET /f/l/ HTTP/1.1" 500 118675
WARNING 2020-07-28 09:38:12,903 log 9236 12112 Not Found: /
WARNING 2020-07-28 09:38:12,904 basehttp 9236 12112 "GET / HTTP/1.1" 404 2026
ERROR 2020-07-28 09:38:22,048 log 9236 12112 Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 9, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2020-07-28 09:38:22,049 basehttp 9236 12112 "GET /f/l/ HTTP/1.1" 500 118675
WARNING 2020-07-28 09:40:56,044 log 8012 8512 Not Found: /
WARNING 2020-07-28 09:40:56,045 basehttp 8012 8512 "GET / HTTP/1.1" 404 2026
WARNING 2020-07-28 09:41:00,029 views 8012 8512 my 1st warning
ERROR 2020-07-28 09:41:00,029 views 8012 8512 my 1st log error
ERROR 2020-07-28 09:41:00,068 log 8012 8512 Internal Server Error: /f/l/
Traceback (most recent call last):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\GGhule\f drive\Logging\MyFistLog\firstlog\views.py", line 13, in flog
    return render(request,context)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "E:\GGhule\f drive\Logging\venv\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\GOPAL GHULE\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
ERROR 2020-07-28 09:41:00,070 basehttp 8012 8512 "GET /f/l/ HTTP/1.1" 500 118847
